name: Release
on:
  push:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    # - uses: dfinity/setup-dfx@main
    - name: Build canisters
      run: |
        rustup target add wasm32-unknown-unknown
        cargo install ic-wasm
        mkdir out
        cargo build --target wasm32-unknown-unknown --release --locked -p idempotent-proxy-canister
        cp target/wasm32-unknown-unknown/release/idempotent_proxy_canister.wasm out/
        cp src/idempotent-proxy-canister/idempotent-proxy-canister.did out/idempotent_proxy_canister.did
        ic-wasm out/idempotent_proxy_canister.wasm -o out/idempotent_proxy_canister.wasm shrink
        ic-wasm out/idempotent_proxy_canister.wasm -o out/idempotent_proxy_canister.wasm optimize O3 --inline-functions-with-loops
        gzip out/idempotent_proxy_canister.wasm
        SHA256="$(sha256sum < "out/idempotent_proxy_canister.wasm.gz" | sed 's/ .*$//g')"
        echo $SHA256 > "out/idempotent_proxy_canister.wasm.gz.$SHA256.txt"
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: out/*
